### ISSUE TITLE
Catch and log exceptions on sent messages?

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor-messaging#5]
Similar in theory to: https://github.com/phosphorjs/phosphor-signaling/issues/7

When posting a message, we have no choice but to rethrow the exception (which causes it to be logged), because posts are executed asynchronously: https://github.com/phosphorjs/phosphor-messaging/blob/master/src/index.ts#L353

I'm thinking we want the same behavior for sent messages as well. That is, when dispatching a message, exceptions are caught and logged, instead of propagated.

Thoughts?

@blink1073 @dwillmer @afshin @ellisonbg @jasongrout

**Comment by dwillmer** [comment]
:+1: for not propagating.

**Comment by afshin** [comment]
I agree with this. Also, I don't like exceptions very much.

**Comment by blink1073** [comment]
Yep, agreed.

**Comment by jasongrout** [comment]
I think it makes sense to keep things consistent between send and post - conceptually, it makes it easier to view them as very similar operations, and also catching exceptions even on send helps separate the sender and receiver as separate objects communicating through messages.
